language: node_js
sudo: false
node_js:
  - "5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
addons:
  firefox: "latest"
notifications:
  email:
    - hello@thiago.me
